### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#18]
The app crashes when I tap on the new setting, see video.

https://github.com/DanielSevillano/music-you/assets/103368536/a204461d-617d-4905-b697-30c50bfa6b9d

**Comment by DanielSevillano** [comment]
That's interesting. Which version of Android are you using?

**Comment by siggi1984** [comment]
> That's interesting. Which version of Android are you using?

Android 12, Samsung Galaxy a21s

**Comment by archit9169** [comment]
It crashes for me as soon as I open the app.

Device: Samsung S23
Abdroid Version: 14
Language: English(India), English(UK)

**Comment by DanielSevillano** [comment]
> It crashes for me as soon as I open the app.

Could you provide the logs, please?

**Comment by archit9169** [comment]
> > It crashes for me as soon as I open the app.
> 
> Could you provide the logs, please?

I tried getting it through logcat apps, but they did not give any conclusive result. Is there any other way without using adb logcat through a pc?

**Comment by DanielSevillano** [comment]
> I tried getting it through logcat apps, but they did not give any conclusive result. Is there any other way without using adb logcat through a pc?

I'm not sure, I thought that adb was necessary to access the logcat.

**Comment by DanielSevillano** [comment]
> The app crashes when I tap on the new setting, see video.

It should be fixed now, a toast will be shown if there's no compatible activity found.

**Comment by siggi1984** [comment]
> > The app crashes when I tap on the new setting, see video.
> 
> It should be fixed now, a toast will be shown if there's no compatible activity found.

Okay, great. Thank you very much.

**Comment by DanielSevillano** [comment]
@siggi1984 Could you please confirm if the issue is fixed in the latest release?

**Comment by siggi1984** [comment]
> @siggi1984 Could you please confirm if the issue is fixed in the latest release?

Unfortunately not, after clicking on the setting the app still crashes.

**Comment by archit9169** [comment]
Okay, so I have fixed my laptop, so I was able to grab the logs using adb logcat.

[MusicYou_CrashLog.txt](https://github.com/DanielSevillano/music-you/files/14896860/MusicYou_CrashLog.txt)

Please have a look, it's crashing as soon as I open it from launcher.

---------

App Version: 0.4

Android Version: 14 (One UI 6.1)
Kernel Version: 5.15.123
Device: Samsung S23 (Snapdragon)

Let me know if anything more is required from my end.

**Comment by DanielSevillano** [comment]
Thank you! I think I have identified and fixed the issue 🥳
It was affecting all devices with Android 14, thank you so much for reporting it.

**Comment by DanielSevillano** [comment]
> Unfortunately not, after clicking on the setting the app still crashes.

Oh, I thought I had identified the issue. Could you please provide the logs?

**Comment by DanielSevillano** [comment]
> Ah, it seems like I was a bit late in providing the logs.

Quite the opposite, you were just in time. I have Android 13 on my device, so I couldn't have identified the issue without your logs.

**Comment by archit9169** [comment]
What was the issue? I tried going through the logs but all I could make out was the intent failing when called from activity.

**Comment by DanielSevillano** [comment]
Android 14 requires registering receivers with intention using a flag (you can read more about this change [here](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported)). You can find the exception in your logs here:

````
04-07 16:16:01.883 14975 14975 E AndroidRuntime: FATAL EXCEPTION: main
04-07 16:16:01.883 14975 14975 E AndroidRuntime: Process: com.github.musicyou, PID: 14975
04-07 16:16:01.883 14975 14975 E AndroidRuntime: java.lang.RuntimeException: Unable to create service it.vfsfitvnm.vimusic.service.PlayerService: java.lang.SecurityException: com.github.musicyou: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:230)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:319)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8919)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
04-07 16:16:01.883 14975 14975 E AndroidRuntime: Caused by: java.lang.SecurityException: com.github.musicyou: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:3053)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:3036)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2978)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6157)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at it.vfsfitvnm.vimusic.service.PlayerService.onCreate(PlayerService.kt:262)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        ... 9 more
04-07 16:16:01.883 14975 14975 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16680)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11613)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2961)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3199)
04-07 16:16:01.883 14975 14975 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1375)
````

**Comment by siggi1984** [comment]
> > Unfortunately not, after clicking on the setting the app still crashes.
> 
> Oh, I thought I had identified the issue. Could you please provide the logs?

FATAL EXCEPTION: main
Process: com.android.settings, PID: 15981
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
	at com.android.settings.applications.intentpicker.AppLaunchSettings.onCreate(AppLaunchSettings.java:142)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2976)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at com.samsung.android.settings.core.SecMultiPaneActivity.onStart(SecMultiPaneActivity.java:203)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8315)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by DanielSevillano** [comment]
I'm not sure about what's causing the NullPointerException. I'll keep trying to fix it.

**Comment by DanielSevillano** [comment]
@archit9169 Could you please confirm if the app works with the latest version?
@siggi1984 I've tried to fix the issue once again. Could you check if it still crashes?

**Comment by siggi1984** [comment]
> @archit9169 Could you please confirm if the app works with the latest version? @siggi1984 I've tried to fix the issue once again. Could you check if it still crashes?

The app still crashes in the new version.

**Comment by DarkCrypt** [comment]
> It crashes for me as soon as I open the app.

V0.5 fixed this issue for me on Android 14.

**Comment by archit9169** [comment]
> @archit9169 Could you please confirm if the app works with the latest version? @siggi1984 I've tried to fix the issue once again. Could you check if it still crashes?

All fixed now. No crashed anywhere in the app for me on android 14.

However, the UI seems to be a little laggy/glitchy. So something to look in the future, hopefully before v1 is released with release keys instead of debug apk.

**Comment by DanielSevillano** [comment]
> The app still crashes in the new version.

Then I'm out of ideas 😞 
I'll let you know if I try something new. At least it isn't a core part of the app.

**Comment by siggi1984** [comment]
> Then I'm out of ideas 😞
> I'll let you know if I try something new. At least it isn't a core part of the app.

All good Bro, don't worry too much, this error is not that big a deal, the app itself works fine.
Maybe it's also because of my cell phone.

**Comment by DanielSevillano** [comment]
> V0.5 fixed this issue for me on Android 14.

> All fixed now. No crashed anywhere in the app for me on android 14.

That's great! I'm glad to hear that 🥳 

> However, the UI seems to be a little laggy/glitchy. So something to look in the future, hopefully before v1 is released with release keys instead of debug apk.

I agree. My focus is on the UI right now, following Material You design guidelines. I want to polish everything before a 1.0 release. If you have any ideas or suggestions, please let me know! 😄

**Comment by DarkCrypt** [comment]
> the UI seems to be a little laggy/glitchy.

Very much so. This issue needs to be priority.

**Comment by DanielSevillano** [comment]
> > the UI seems to be a little laggy/glitchy.
> 
> Very much so. This issue needs to be priority.

Are there any specific parts of the app where you are noticing that?

**Comment by DarkCrypt** [comment]
> Are there any specific parts of the app where you are noticing that?

Within the search tabs. Initial loading of results are quick but additional loading (when scrolling down) has a severe lag.

**Comment by DanielSevillano** [comment]
You are right, I'll try to improve the search experience. Thanks!
